# Generated by Django 5.0.6 on 2024-07-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0004_alter_det_result_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='det_model',
            name='file',
            field=models.FileField(default=None, upload_to='detect_photo/before'),
        ),
    ]
